@startuml core.puml
title Core - Racetrack Core Class Diagram

class Engine
{
	+init()
	+run()
	+shutdown()
}

class World
{
	+for_each_entity<T,Fn>( Fn&& fn )
	+get_component<T>( Entity e )
	+view<Ts...>() : View
}

class Registry
{
	-World& world

	+create_entity() : Entity
	+remove_entity( Entity )

	+register_component<T>( const std::string& )
    +create_component( Entity, const std::string& ) : bool
	+with_component( Entity, const std::string&, std::function<void(void*)>&& ) : bool
    +remove_component( Entity, const std::string& ) : bool

    +flush() : bool
    +clear()
}

class View
{
	-const World&

	+begin() : View::Iterator
	+end() : View::Iterator
}

struct View::Iterator
{
	operator*()
	operator++()
	operator!=()
}

class Timing
{
	+elapsed() : double
}

class CommandQueue
{
	+push( std::unique_ptr<ICommand> )
	+execute( Engine& )
}

class InputQueue
{
	+push( std::unique_ptr<IEvent> )
	+process( Engine& )
}

interface IEvent
interface ICommand
interface ISystem

Registry -> World : references

View *- View::Iterator
World <-- View : references

InputQueue o-- "0..*" IEvent
CommandQueue o-- "0..*" ICommand
Engine o-- "0..*" ISystem

Engine *--- World
Engine *--- Registry
Timing -* Engine
Engine *- CommandQueue
Engine *- InputQueue

@enduml